baseURL: "https://arunima-sen.github.io/" 
title: Arunima Sen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Background
          url: background/
          weight: 1 
        - name: Recognition
          url: recognition/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: CV
          url: Sen_CV.pdf
          weight: 4
     

params:
    description: "Hi! I am Arunima."
    author: Arunima Sen
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Arunima Sen
          subtitle: 'Hi! I am Arunima, a student in the Erasmus Mundus <span style="font-weight: bold; color: #2558b3;">Copernicus Master in Digital Earth</span> program at Paris Lodron University Salzburg and the University of Southern Brittany, supported as an <span style="font-weight: bold; color: #2558b3;">Erasmus Mundus</span> Scholar fully funded by the European Union. I am currently studying <span style="font-weight: bold; color: #2558b3;">Earth Observation</span> and <span style="font-weight: bold; color: #2558b3;">Geoinformatics</span> and will specialize in <span style="font-weight: bold; color: #2558b3;">Geo Data Science</span> and <span style="font-weight: bold; color: #2558b3;">AI</span> next year. I am interested in understanding <span style="font-weight: bold; color: #2558b3;">Earth system science</span>, geophysical hazards, and climate dynamics; particularly how various components interact and influence one another, as well as their broader impacts on the Earth and society, using <span style="font-weight: bold; color: #2558b3;">geospatial</span> and <span style="font-weight: bold; color: #2558b3;">computational</span> approaches.
              <br><br>
              <div style="display: flex; gap: 20px; justify-content: center;">
               <img src="logo1.jpg" alt="Logo 1" style="width: 120px; height: 60px; object-fit: cover;">
               <img src="logo2.png" alt="Logo 2" style="width: 120px; height: 60px; object-fit: cover;">
               <img src="logo3.png" alt="Logo 3" style="width: 120px; height: 60px; object-fit: cover;">
              </div>'
              
    

          imageUrl: "picture.jpeg"
          # [Copernicus Master in Digital Earth](https://master-cde.eu/)
          

          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Background
              url: background/
            - name: Recognition
              url: recognition/
            - name: Projects
              url: projects/
            - name: CV
              url: Sen_CV.pdf
            

    socialIcons:
        - name: Email
          url: mailto:arunimasen2001@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/arunimasen/
        - name: GitHub
          url: https://github.com/arunima-sen 
        - name: CV
          url: Sen_CV.pdf


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Arunima Sen"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
