baseURL: "https://arunima-sen.github.io/" 
title: Arunima Sen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Experience
          url: talks/
          weight: 1 
        - name: Projects
          url: projects/
          weight: 2
        - name: CV
          url: Sen_CV.pdf
          weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "Hi! I am Arunima."
    author: Arunima Sen
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Arunima Sen
          subtitle: "Hi! I am Arunima, a student in the Erasmus Mundus Copernicus Master in Digital Earth program at Paris Lodron University Salzburg and the University of Southern Brittany, supported as an Erasmus Mundus Scholar fully funded by the European Union. I am currently studying Earth Observation and Geoinformatics and will specialize in Geo Data Science and AI next year. My interests lie in understanding Earth system science, geophysical hazards, and climate dynamics—particularly how various components interact and influence one another, as well as their broader impacts on the Earth and society. I aim to explore these topics using geospatial and computational approaches.
"
          imageUrl: "headshot.JPG"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Experience
              url: talks/
            - name: Projects
              url: projects/
            - name: CV
              url: Sen_CV.pdf
            

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:arunimasen2001@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/arunimasen/


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Arunima Sen"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
